all: true
check-coverage: true
include:
  - src
exclude:
  - src/*/infrastructure
  - src/**/*.d.ts
statements: 85
branches: 64
functions: 82
lines: 87
watermarks:
  branches: [90, 100]
  lines: [90, 100]
  functions: [90, 100]
  statements: [90, 100]
